language: node_js
node_js:
  - '10'
dist: trusty
cache:
  directories:
    - node_modules
install:
  - npm install

jobs:
  include:
    - stage: build
      script: npm run build
    - stage: test
      # services:
      #   - xvfb
      # addons:
      #   firefox: "66.0"
      #   chrome: stable
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: 
        - npm run test
        # - xvfb-run npm run test:browsers
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
